import { Word } from './types';

export const croatianPhrases: Word[] = [
  // Social
  { id: 'phrase-1', croatian: 'Dobar dan!', english: 'Good day!', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-2', croatian: 'Kako ste?', english: 'How are you? (formal)', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-3', croatian: 'Ja sam dobro, hvala.', english: 'I am well, thank you.', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-4', croatian: 'Drago mi je.', english: 'Nice to meet you.', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-5', croatian: 'Oprostite.', english: 'Excuse me / I\'m sorry.', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-6', croatian: 'Molim.', english: 'Please / You\'re welcome.', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-7', croatian: 'Hvala lijepo.', english: 'Thank you very much.', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-8', croatian: 'Doviđenja!', english: 'Goodbye!', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-9', croatian: 'Laku noć.', english: 'Good night.', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-10', croatian: 'Vidimo se uskoro.', english: 'See you soon.', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-11', croatian: 'Kako se zovete?', english: 'What is your name? (formal)', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-12', croatian: 'Zovem se [Ime].', english: 'My name is [Name].', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-13', croatian: 'Odakle ste?', english: 'Where are you from? (formal)', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-14', croatian: 'Ja sam iz [Zemlja].', english: 'I am from [Country].', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-15', croatian: 'Govorite li engleski?', english: 'Do you speak English? (formal)', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-16', croatian: 'Malo govorim hrvatski.', english: 'I speak a little Croatian.', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-17', croatian: 'Ne razumijem.', english: 'I don\'t understand.', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-18', croatian: 'Možete li ponoviti?', english: 'Can you repeat that? (formal)', category: 'Social', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-19', croatian: 'Pomoć!', english: 'Help!', category: 'Emergency', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-20', croatian: 'Gdje je WC?', english: 'Where is the restroom?', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },

  // Restaurant
  { id: 'phrase-21', croatian: 'Imate li slobodan stol?', english: 'Do you have a free table?', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-22', croatian: 'Želio bih rezervirati stol.', english: 'I would like to reserve a table.', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-23', croatian: 'Jelovnik, molim.', english: 'The menu, please.', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-24', croatian: 'Što preporučujete?', english: 'What do you recommend?', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-25', croatian: 'Ja bih [Jelo].', english: 'I would like [Dish].', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-26', croatian: 'Vodu, molim.', english: 'Water, please.', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-27', croatian: 'Račun, molim.', english: 'The bill, please.', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-28', croatian: 'Je li uključena usluga?', english: 'Is service included?', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-29', croatian: 'Bilo je ukusno!', english: 'It was delicious!', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-30', croatian: 'Dobar tek!', english: 'Enjoy your meal!', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-31', croatian: 'Imate li vegetarijanska jela?', english: 'Do you have vegetarian dishes?', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-32', croatian: 'Bez luka, molim.', english: 'Without onion, please.', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-33', croatian: 'Još jedno pivo, molim.', english: 'Another beer, please.', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-34', croatian: 'Mogu li platiti karticom?', english: 'Can I pay by card?', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-35', croatian: 'Hvala na usluzi.', english: 'Thank you for the service.', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-36', croatian: 'Gdje je najbliži restoran?', english: 'Where is the nearest restaurant?', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-37', croatian: 'Imate li dječju stolicu?', english: 'Do you have a high chair?', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-38', croatian: 'Ovo je za mene.', english: 'This is for me.', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-39', croatian: 'Nije ljuto.', english: 'It\'s not spicy.', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-40', croatian: 'Samo malo.', english: 'Just a little.', category: 'Restaurant', favorite: false, correct: 0, incorrect: 0 },

  // Travel
  { id: 'phrase-41', croatian: 'Gdje je [Mjesto]?', english: 'Where is [Place]?', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-42', croatian: 'Koliko je daleko?', english: 'How far is it?', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-43', croatian: 'Možete li mi pokazati na karti?', english: 'Can you show me on the map?', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-44', croatian: 'Skrenite lijevo/desno.', english: 'Turn left/right.', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-45', croatian: 'Ravno naprijed.', english: 'Straight ahead.', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-46', croatian: 'Autobusna stanica.', english: 'Bus stop.', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-47', croatian: 'Željeznička stanica.', english: 'Train station.', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-48', croatian: 'Zračna luka.', english: 'Airport.', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-49', croatian: 'Taksi, molim.', english: 'Taxi, please.', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-50', croatian: 'Koliko košta karta?', english: 'How much is the ticket?', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-51', croatian: 'Imate li sobu?', english: 'Do you have a room?', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-52', croatian: 'Želim sobu za jednu/dvije osobe.', english: 'I want a room for one/two people.', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-53', croatian: 'Koliko košta noćenje?', english: 'How much is one night?', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-54', croatian: 'Doručak je uključen?', english: 'Is breakfast included?', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-55', croatian: 'Prijava/Odjava.', english: 'Check-in/Check-out.', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-56', croatian: 'Imate li internet?', english: 'Do you have internet?', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-57', croatian: 'Gdje mogu kupiti kartu?', english: 'Where can I buy a ticket?', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-58', croatian: 'Kada polazi autobus?', english: 'When does the bus depart?', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-59', croatian: 'Kada dolazi vlak?', english: 'When does the train arrive?', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-60', croatian: 'Sretan put!', english: 'Have a good trip!', category: 'Travel', favorite: false, correct: 0, incorrect: 0 },

  // Market/Shopping
  { id: 'phrase-61', croatian: 'Koliko košta ovo?', english: 'How much does this cost?', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-62', croatian: 'Mogu li probati?', english: 'Can I try it on?', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-63', croatian: 'Imate li manji/veći broj?', english: 'Do you have a smaller/larger size?', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-64', croatian: 'Želim kupiti [Stvar].', english: 'I want to buy [Thing].', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-65', croatian: 'To je preskupo.', english: 'That is too expensive.', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-66', croatian: 'Možete li sniziti cijenu?', english: 'Can you lower the price?', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-67', croatian: 'Plaćam gotovinom.', english: 'I\'m paying with cash.', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-68', croatian: 'Plaćam karticom.', english: 'I\'m paying with card.', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-69', croatian: 'Hvala na kupnji.', english: 'Thank you for your purchase.', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-70', croatian: 'Gdje je blagajna?', english: 'Where is the cashier?', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-71', croatian: 'Imate li kruha?', english: 'Do you have bread?', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-72', croatian: 'Kilogram jabuka, molim.', english: 'A kilogram of apples, please.', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-73', croatian: 'Želim ovo.', english: 'I want this.', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-74', croatian: 'Imate li popust?', english: 'Do you have a discount?', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-75', croatian: 'Hvala, to je sve.', english: 'Thank you, that\'s all.', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-76', croatian: 'Gdje je tržnica?', english: 'Where is the market?', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-77', croatian: 'Ovo je svježe.', english: 'This is fresh.', category: 'Market/Shopping', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-78', croatian: 'Trebam pomoć.', english: 'I need help.', category: 'Emergency', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-79', croatian: 'Izgubio sam se.', english: 'I am lost.', category: 'Emergency', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-80', croatian: 'Pozovite policiju/hitnu pomoć.', english: 'Call the police/ambulance.', category: 'Emergency', favorite: false, correct: 0, incorrect: 0 },

  // Emergency
  { id: 'phrase-81', croatian: 'Doktor, molim.', english: 'Doctor, please.', category: 'Emergency', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-82', croatian: 'Boli me [Dio tijela].', english: 'My [Body part] hurts.', category: 'Emergency', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-83', croatian: 'Imam alergiju na [Stvar].', english: 'I have an allergy to [Thing].', category: 'Emergency', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-84', croatian: 'Ukradena mi je torba.', english: 'My bag was stolen.', category: 'Emergency', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-85', croatian: 'Gdje je bolnica?', english: 'Where is the hospital?', category: 'Emergency', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-86', croatian: 'Opasnost!', english: 'Danger!', category: 'Emergency', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-87', croatian: 'Vatra!', english: 'Fire!', category: 'Emergency', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-88', croatian: 'Hitno je.', english: 'It\'s urgent.', category: 'Emergency', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-89', croatian: 'Ne mogu pronaći [Osoba/Stvar].', english: 'I cannot find [Person/Thing].', category: 'Emergency', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-90', croatian: 'Trebam lijek.', english: 'I need medicine.', category: 'Emergency', favorite: false, correct: 0, incorrect: 0 },

  // Small Talk
  { id: 'phrase-91', croatian: 'Kako je vrijeme?', english: 'How is the weather?', category: 'Small Talk', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-92', croatian: 'Lijepo vrijeme, zar ne?', english: 'Nice weather, isn\'t it?', category: 'Small Talk', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-93', croatian: 'Odlično!', english: 'Excellent!', category: 'Small Talk', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-94', croatian: 'Nije loše.', english: 'Not bad.', category: 'Small Talk', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-95', croatian: 'Što ima novo?', english: 'What\'s new?', category: 'Small Talk', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-96', croatian: 'Ništa posebno.', english: 'Nothing special.', category: 'Small Talk', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-97', croatian: 'Uživajte u danu!', english: 'Enjoy your day!', category: 'Small Talk', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-98', croatian: 'Sretno!', english: 'Good luck!', category: 'Small Talk', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-99', croatian: 'Živjeli!', english: 'Cheers!', category: 'Small Talk', favorite: false, correct: 0, incorrect: 0 },
  { id: 'phrase-100', croatian: 'Doviđenja!', english: 'Goodbye!', category: 'Small Talk', favorite: false, correct: 0, incorrect: 0 },
];