import { Flashcard } from "./types";

export const STARTER_PACK: Flashcard[] = [
  // GREETINGS
  { id: "g1", croatian: "Zdravo", english: "Hello", category: "Greetings" },
  { id: "g2", croatian: "Bok", english: "Hi / Bye", category: "Greetings" },
  { id: "g3", croatian: "Dobro jutro", english: "Good morning", category: "Greetings" },
  { id: "g4", croatian: "Dobar dan", english: "Good day", category: "Greetings" },
  { id: "g5", croatian: "Dobra večer", english: "Good evening", category: "Greetings" },
  { id: "g6", croatian: "Laku noć", english: "Good night", category: "Greetings" },
  { id: "g7", croatian: "Kako si?", english: "How are you? (informal)", category: "Greetings" },
  { id: "g8", croatian: "Kako ste?", english: "How are you? (formal)", category: "Greetings" },
  { id: "g9", croatian: "Dobro sam", english: "I am fine", category: "Greetings" },
  { id: "g10", croatian: "Drago mi je", english: "Pleased to meet you", category: "Greetings" },
  { id: "g11", croatian: "Vidimo se!", english: "See you!", category: "Greetings" },
  { id: "g12", croatian: "Doviđenja", english: "Goodbye", category: "Greetings" },
  { id: "g13", croatian: "Što ima?", english: "What's up?", category: "Greetings" },
  { id: "g14", croatian: "Nije loše", english: "Not bad", category: "Greetings" },
  { id: "g15", croatian: "Sve najbolje", english: "All the best", category: "Greetings" },

  // POLITENESS (Hvala, Molim, etc.)
  { id: "p1", croatian: "Hvala", english: "Thank you", category: "Politeness" },
  { id: "p2", croatian: "Hvala lijepa", english: "Thank you very much", category: "Politeness" },
  { id: "p3", croatian: "Puno hvala", english: "Thanks a lot", category: "Politeness" },
  { id: "p4", croatian: "Molim", english: "Please / You're welcome", category: "Politeness" },
  { id: "p5", croatian: "Nema na čemu", english: "Don't mention it / You're welcome", category: "Politeness" },
  { id: "p6", croatian: "Oprostite", english: "Excuse me / I'm sorry (formal)", category: "Politeness" },
  { id: "p7", croatian: "Oprosti", english: "Sorry (informal)", category: "Politeness" },
  { id: "p8", croatian: "Žao mi je", english: "I'm sorry", category: "Politeness" },
  { id: "p9", croatian: "Izvolite", english: "Here you go (formal)", category: "Politeness" },
  { id: "p10", croatian: "Izvoli", english: "Here you go (informal)", category: "Politeness" },
  { id: "p11", croatian: "U redu je", english: "It's okay", category: "Politeness" },
  { id: "p12", croatian: "Sretno!", english: "Good luck!", category: "Politeness" },
  { id: "p13", croatian: "Čestitam!", english: "Congratulations!", category: "Politeness" },
  { id: "p14", croatian: "Možete li mi pomoći?", english: "Can you help me?", category: "Politeness" },
  { id: "p15", croatian: "Naravno", english: "Of course", category: "Politeness" },

  // NUMBERS (1-20, 30, 40, 50, 100, 1000)
  { id: "n1", croatian: "Jedan", english: "One", category: "Numbers" },
  { id: "n2", croatian: "Dva", english: "Two", category: "Numbers" },
  { id: "n3", croatian: "Tri", english: "Three", category: "Numbers" },
  { id: "n4", croatian: "Četiri", english: "Four", category: "Numbers" },
  { id: "n5", croatian: "Pet", english: "Five", category: "Numbers" },
  { id: "n6", croatian: "Šest", english: "Six", category: "Numbers" },
  { id: "n7", croatian: "Sedam", english: "Seven", category: "Numbers" },
  { id: "n8", croatian: "Osam", english: "Eight", category: "Numbers" },
  { id: "n9", croatian: "Devet", english: "Nine", category: "Numbers" },
  { id: "n10", croatian: "Deset", english: "Ten", category: "Numbers" },
  { id: "n11", croatian: "Jedanaest", english: "Eleven", category: "Numbers" },
  { id: "n12", croatian: "Dvanaest", english: "Twelve", category: "Numbers" },
  { id: "n13", croatian: "Trinaest", english: "Thirteen", category: "Numbers" },
  { id: "n14", croatian: "Četrnaest", english: "Fourteen", category: "Numbers" },
  { id: "n15", croatian: "Petnaest", english: "Fifteen", category: "Numbers" },
  { id: "n16", croatian: "Šesnaest", english: "Sixteen", category: "Numbers" },
  { id: "n17", croatian: "Sedamnaest", english: "Seventeen", category: "Numbers" },
  { id: "n18", croatian: "Osamnaest", english: "Eighteen", category: "Numbers" },
  { id: "n19", croatian: "Devetnaest", english: "Nineteen", category: "Numbers" },
  { id: "n20", croatian: "Dvadeset", english: "Twenty", category: "Numbers" },
  { id: "n21", croatian: "Trideset", english: "Thirty", category: "Numbers" },
  { id: "n22", croatian: "Četrdeset", english: "Forty", category: "Numbers" },
  { id: "n23", croatian: "Pedeset", english: "Fifty", category: "Numbers" },
  { id: "n24", croatian: "Sto", english: "Hundred", category: "Numbers" },
  { id: "n25", croatian: "Tisuću", english: "Thousand", category: "Numbers" },

  // COMMON SENTENCES
  { id: "s1", croatian: "Govorite li engleski?", english: "Do you speak English?", category: "Common Sentences" },
  { id: "s2", croatian: "Ne razumijem", english: "I don't understand", category: "Common Sentences" },
  { id: "s3", croatian: "Možete li ponoviti?", english: "Can you repeat?", category: "Common Sentences" },
  { id: "s4", croatian: "Kako se kaže...?", english: "How do you say...?", category: "Common Sentences" },
  { id: "s5", croatian: "Što to znači?", english: "What does that mean?", category: "Common Sentences" },
  { id: "s6", croatian: "Zovem se...", english: "My name is...", category: "Common Sentences" },
  { id: "s7", croatian: "Odakle ste?", english: "Where are you from?", category: "Common Sentences" },
  { id: "s8", croatian: "Ja sam iz...", english: "I am from...", category: "Common Sentences" },
  { id: "s9", croatian: "Gdje je zahod?", english: "Where is the bathroom?", category: "Common Sentences" },
  { id: "s10", croatian: "Koliko je sati?", english: "What time is it?", category: "Common Sentences" },
  { id: "s11", croatian: "Drago mi je što smo se upoznali", english: "Nice to meet you", category: "Common Sentences" },
  { id: "s12", croatian: "Što radite?", english: "What are you doing?", category: "Common Sentences" },
  { id: "s13", croatian: "Slažem se", english: "I agree", category: "Common Sentences" },
  { id: "s14", croatian: "Ne slažem se", english: "I don't agree", category: "Common Sentences" },
  { id: "s15", croatian: "Možda", english: "Maybe", category: "Common Sentences" },
  { id: "s16", croatian: "Naravno da ne", english: "Of course not", category: "Common Sentences" },
  { id: "s17", croatian: "Nema problema", english: "No problem", category: "Common Sentences" },
  { id: "s18", croatian: "Sve je u redu", english: "Everything is fine", category: "Common Sentences" },
  { id: "s19", croatian: "Želim vam ugodan dan", english: "Have a nice day", category: "Common Sentences" },
  { id: "s20", croatian: "Vidimo se kasnije!", english: "See you later!", category: "Common Sentences" },

  // DIALOGUES
  { id: "d1", croatian: "Dobar dan, kako ste?", english: "Good day, how are you?", category: "Dialogues" },
  { id: "d2", croatian: "Dobro sam, hvala. A vi?", english: "I'm fine, thanks. And you?", category: "Dialogues" },
  { id: "d3", croatian: "I ja sam dobro", english: "I'm fine too", category: "Dialogues" },
  { id: "d4", croatian: "Oprostite, govorite li engleski?", english: "Excuse me, do you speak English?", category: "Dialogues" },
  { id: "d5", croatian: "Samo malo", english: "Only a little", category: "Dialogues" },
  { id: "d6", croatian: "Gdje se nalazi najbliža ljekarna?", english: "Where is the nearest pharmacy?", category: "Dialogues" },
  { id: "d7", croatian: "Tamo, preko puta ulice", english: "There, across the street", category: "Dialogues" },
  { id: "d8", croatian: "Hvala vam puno", english: "Thank you very much", category: "Dialogues" },
  { id: "d9", croatian: "Nema na čemu", english: "You're welcome", category: "Dialogues" },
  { id: "d10", croatian: "Što želite popiti?", english: "What would you like to drink?", category: "Dialogues" },
  { id: "d11", croatian: "Kavu, molim", english: "A coffee, please", category: "Dialogues" },
  { id: "d12", croatian: "S mlijekom ili bez?", english: "With milk or without?", category: "Dialogues" },
  { id: "d13", croatian: "Bez mlijeka, hvala", english: "Without milk, thank you", category: "Dialogues" },
  { id: "d14", croatian: "Koliko košta ovaj suvenir?", english: "How much is this souvenir?", category: "Dialogues" },
  { id: "d15", croatian: "Pedeset kuna (eura)", english: "Fifty kuna (euros)", category: "Dialogues" },
  { id: "d16", croatian: "Mogu li platiti karticom?", english: "Can I pay by card?", category: "Dialogues" },
  { id: "d17", croatian: "Nažalost, samo gotovina", english: "Unfortunately, cash only", category: "Dialogues" },
  { id: "d18", croatian: "U redu, evo izvolite", english: "Okay, here you go", category: "Dialogues" },
  { id: "d19", croatian: "Hvala, ugodan dan!", english: "Thanks, have a nice day!", category: "Dialogues" },
  { id: "d20", croatian: "Hvala, također!", english: "Thanks, you too!", category: "Dialogues" },

  // TRAVEL
  { id: "t1", croatian: "Karta", english: "Ticket", category: "Travel" },
  { id: "t2", croatian: "Povratna karta", english: "Round-trip ticket", category: "Travel" },
  { id: "t3", croatian: "Putovnica", english: "Passport", category: "Travel" },
  { id: "t4", croatian: "Zračna luka", english: "Airport", category: "Travel" },
  { id: "t5", croatian: "Kolodvor", english: "Station", category: "Travel" },
  { id: "t6", croatian: "Autobus", english: "Bus", category: "Travel" },
  { id: "t7", croatian: "Vlak", english: "Train", category: "Travel" },
  { id: "t8", croatian: "Taksi", english: "Taxi", category: "Travel" },
  { id: "t9", croatian: "Hotel", english: "Hotel", category: "Travel" },
  { id: "t10", croatian: "Rezervacija", english: "Reservation", category: "Travel" },
  { id: "t11", croatian: "Gdje je...?", english: "Where is...?", category: "Travel" },
  { id: "t12", croatian: "Lijevo", english: "Left", category: "Travel" },
  { id: "t13", croatian: "Desno", english: "Right", category: "Travel" },
  { id: "t14", croatian: "Ravno", english: "Straight ahead", category: "Travel" },
  { id: "t15", croatian: "Ulica", english: "Street", category: "Travel" },
  { id: "t16", croatian: "Trg", english: "Square", category: "Travel" },
  { id: "t17", croatian: "Centar grada", english: "City center", category: "Travel" },
  { id: "t18", croatian: "Karta grada", english: "City map", category: "Travel" },
  { id: "t19", croatian: "Izlaz", english: "Exit", category: "Travel" },
  { id: "t20", croatian: "Ulaz", english: "Entrance", category: "Travel" },

  // FOOD & DRINK
  { id: "fd1", croatian: "Hrana", english: "Food", category: "Food & Drink" },
  { id: "fd2", croatian: "Piće", english: "Drink", category: "Food & Drink" },
  { id: "fd3", croatian: "Voda", english: "Water", category: "Food & Drink" },
  { id: "fd4", croatian: "Kruh", english: "Bread", category: "Food & Drink" },
  { id: "fd5", croatian: "Mlijeko", english: "Milk", category: "Food & Drink" },
  { id: "fd6", croatian: "Kava", english: "Coffee", category: "Food & Drink" },
  { id: "fd7", croatian: "Čaj", english: "Tea", category: "Food & Drink" },
  { id: "fd8", croatian: "Vino", english: "Wine", category: "Food & Drink" },
  { id: "fd9", croatian: "Pivo", english: "Beer", category: "Food & Drink" },
  { id: "fd10", croatian: "Sok", english: "Juice", category: "Food & Drink" },
  { id: "fd11", croatian: "Restoran", english: "Restaurant", category: "Food & Drink" },
  { id: "fd12", croatian: "Jelovnik", english: "Menu", category: "Food & Drink" },
  { id: "fd13", croatian: "Račun, molim", english: "The check, please", category: "Food & Drink" },
  { id: "fd14", croatian: "Doručak", english: "Breakfast", category: "Food & Drink" },
  { id: "fd15", croatian: "Ručak", english: "Lunch", category: "Food & Drink" },
  { id: "fd16", croatian: "Večera", english: "Dinner", category: "Food & Drink" },
  { id: "fd17", croatian: "Meso", english: "Meat", category: "Food & Drink" },
  { id: "fd18", croatian: "Riba", english: "Fish", category: "Food & Drink" },
  { id: "fd19", croatian: "Povrće", english: "Vegetables", category: "Food & Drink" },
  { id: "fd20", croatian: "Voće", english: "Fruit", category: "Food & Drink" },
  { id: "fd21", croatian: "Jabuka", english: "Apple", category: "Food & Drink" },
  { id: "fd22", croatian: "Banana", english: "Banana", category: "Food & Drink" },
  { id: "fd23", croatian: "Sir", english: "Cheese", category: "Food & Drink" },
  { id: "fd24", croatian: "Jaja", english: "Eggs", category: "Food & Drink" },
  { id: "fd25", croatian: "Sol", english: "Salt", category: "Food & Drink" },
  { id: "fd26", croatian: "Papar", english: "Pepper", category: "Food & Drink" },
  { id: "fd27", croatian: "Slatko", english: "Sweet", category: "Food & Drink" },
  { id: "fd28", croatian: "Slano", english: "Salty", category: "Food & Drink" },
  { id: "fd29", croatian: "Ljuto", english: "Spicy", category: "Food & Drink" },
  { id: "fd30", croatian: "Ukusan", english: "Delicious", category: "Food & Drink" },

  // TIME
  { id: "tm1", croatian: "Vrijeme", english: "Time", category: "Time" },
  { id: "tm2", croatian: "Danas", english: "Today", category: "Time" },
  { id: "tm3", croatian: "Sutra", english: "Tomorrow", category: "Time" },
  { id: "tm4", croatian: "Jučer", english: "Yesterday", category: "Time" },
  { id: "tm5", croatian: "Sada", english: "Now", category: "Time" },
  { id: "tm6", croatian: "Kasnije", english: "Later", category: "Time" },
  { id: "tm7", croatian: "Ujutro", english: "In the morning", category: "Time" },
  { id: "tm8", croatian: "Popodne", english: "In the afternoon", category: "Time" },
  { id: "tm9", croatian: "Navečer", english: "In the evening", category: "Time" },
  { id: "tm10", croatian: "Noć", english: "Night", category: "Time" },
  { id: "tm11", croatian: "Tjedan", english: "Week", category: "Time" },
  { id: "tm12", croatian: "Mjesec", english: "Month", category: "Time" },
  { id: "tm13", croatian: "Godina", english: "Year", category: "Time" },
  { id: "tm14", croatian: "Ponedjeljak", english: "Monday", category: "Time" },
  { id: "tm15", croatian: "Utorak", english: "Tuesday", category: "Time" },
  { id: "tm16", croatian: "Srijeda", english: "Wednesday", category: "Time" },
  { id: "tm17", croatian: "Četvrtak", english: "Thursday", category: "Time" },
  { id: "tm18", croatian: "Petak", english: "Friday", category: "Time" },
  { id: "tm19", croatian: "Subota", english: "Saturday", category: "Time" },
  { id: "tm20", croatian: "Nedjelja", english: "Sunday", category: "Time" },

  // FAMILY
  { id: "fam1", croatian: "Obitelj", english: "Family", category: "Family" },
  { id: "fam2", croatian: "Otac", english: "Father", category: "Family" },
  { id: "fam3", croatian: "Majka", english: "Mother", category: "Family" },
  { id: "fam4", croatian: "Brat", english: "Brother", category: "Family" },
  { id: "fam5", croatian: "Sestra", english: "Sister", category: "Family" },
  { id: "fam6", croatian: "Sin", english: "Son", category: "Family" },
  { id: "fam7", croatian: "Kći", english: "Daughter", category: "Family" },
  { id: "fam8", croatian: "Djed", english: "Grandfather", category: "Family" },
  { id: "fam9", croatian: "Baka", english: "Grandmother", category: "Family" },
  { id: "fam10", croatian: "Suprug", english: "Husband", category: "Family" },
  { id: "fam11", croatian: "Supruga", english: "Wife", category: "Family" },
  { id: "fam12", croatian: "Prijatelj", english: "Friend", category: "Family" },

  // ADJECTIVES
  { id: "adj1", croatian: "Velik", english: "Big", category: "Adjectives" },
  { id: "adj2", croatian: "Malen", english: "Small", category: "Adjectives" },
  { id: "adj3", croatian: "Dobar", english: "Good", category: "Adjectives" },
  { id: "adj4", croatian: "Loš", english: "Bad", category: "Adjectives" },
  { id: "adj5", croatian: "Lijep", english: "Beautiful", category: "Adjectives" },
  { id: "adj6", croatian: "Ružan", english: "Ugly", category: "Adjectives" },
  { id: "adj7", croatian: "Sretan", english: "Happy", category: "Adjectives" },
  { id: "adj8", croatian: "Tužan", english: "Sad", category: "Adjectives" },
  { id: "adj9", croatian: "Nov", english: "New", category: "Adjectives" },
  { id: "adj10", croatian: "Star", english: "Old", category: "Adjectives" },
  { id: "adj11", croatian: "Skup", english: "Expensive", category: "Adjectives" },
  { id: "adj12", croatian: "Jeftin", english: "Cheap", category: "Adjectives" },
  { id: "adj13", croatian: "Brz", english: "Fast", category: "Adjectives" },
  { id: "adj14", croatian: "Spor", english: "Slow", category: "Adjectives" },
  { id: "adj15", croatian: "Vruć", english: "Hot", category: "Adjectives" },
  { id: "adj16", croatian: "Hladan", english: "Cold", category: "Adjectives" },
  { id: "adj17", croatian: "Pun", english: "Full", category: "Adjectives" },
  { id: "adj18", croatian: "Prazan", english: "Empty", category: "Adjectives" },
  { id: "adj19", croatian: "Lagan", english: "Easy / Light", category: "Adjectives" },
  { id: "adj20", croatian: "Težak", english: "Difficult / Heavy", category: "Adjectives" },

  // VERBS
  { id: "v1", croatian: "Biti", english: "To be", category: "Verbs" },
  { id: "v2", croatian: "Imati", english: "To have", category: "Verbs" },
  { id: "v3", croatian: "Htjeti", english: "To want", category: "Verbs" },
  { id: "v4", croatian: "Ići", english: "To go", category: "Verbs" },
  { id: "v5", croatian: "Dolaziti", english: "To come", category: "Verbs" },
  { id: "v6", croatian: "Vidjeti", english: "To see", category: "Verbs" },
  { id: "v7", croatian: "Čuti", english: "To hear", category: "Verbs" },
  { id: "v8", croatian: "Govoriti", english: "To speak / talk", category: "Verbs" },
  { id: "v9", croatian: "Pisati", english: "To write", category: "Verbs" },
  { id: "v10", croatian: "Čitati", english: "To read", category: "Verbs" },
  { id: "v11", croatian: "Učiti", english: "To learn", category: "Verbs" },
  { id: "v12", croatian: "Raditi", english: "To work / do", category: "Verbs" },
  { id: "v13", croatian: "Spavati", english: "To sleep", category: "Verbs" },
  { id: "v14", croatian: "Jesti", english: "To eat", category: "Verbs" },
  { id: "v15", croatian: "Piti", english: "To drink", category: "Verbs" },
  { id: "v16", croatian: "Kupiti", english: "To buy", category: "Verbs" },
  { id: "v17", croatian: "Prodati", english: "To sell", category: "Verbs" },
  { id: "v18", croatian: "Razumjeti", english: "To understand", category: "Verbs" },
  { id: "v19", croatian: "Misliti", english: "To think", category: "Verbs" },
  { id: "v20", croatian: "Znati", english: "To know", category: "Verbs" },

  // SPECIAL PHRASES
  { id: "sp1", croatian: "Pomalo", english: "It is what it is", category: "Special Phrases" },
];
